@Echo Off
setlocal enabledelayedexpansion

Title Qompiler v0.9

:Start

If Not Exist *.MAP GoTo NeedMaps
If Not Exist tools\qbsp.exe GoTo NoTools
If Not Exist tools\vis.exe GoTo NoTools
If Not Exist tools\light.exe GoTo NoTools
If Not Exist Docs\Nul MD Docs
If Not Exist Qompiled\Nul MD Qompiled
If Not Exist Maps\Nul MD Maps
If Not Exist Logs\Nul MD Logs
If Not Exist Configs\Nul MD Configs
If Exist "visdescription.bat" Move "visdescription.bat" "Docs"
If Exist "lightdescription.bat" Move "lightdescription.bat" "Docs"
If Exist "qbspdescription.bat" Move "qbspdescription.bat" "Docs"
If Exist "muk.bat" move "muk.bat" "Configs"
If "%1"=="DoIt" GoTo Qompile
If Not "%1"=="" GoTo NeedMaps

Echo Log file for Qompiler>Logs\QompilerLog.txt
Echo.>>Logs\QompilerLog.txt

Echo Lets Qompile some maps!
Echo.
Echo Do you want to load a config?
Echo.
Echo Making a config will let you use the same settings for your compiling tools 
Echo in the future, without having to reapply them.
Echo.
Set /p _config=Type a config name to load. If it doesnt exist, we'll create one!
Echo.
If Exist Configs\%_config%.bat GoTo Run 
If Not Exist configs\%_config%.bat Goto Settings

:Overwrite
Echo.
Echo	The config %_config% already exists.
Echo.
Set /p _rename="[O]verwrite old config -or- [R]ename current?"
if /I "%_rename%"=="o" goto settings
if /I "%_rename%"=="r" goto NewConfig

:Settings

Call docs\qbspdescription.bat
Set /p _qbsp=Input any desired qbsp settings, then press "Enter" to continue...
Echo.
Call docs\visdescription.bat
Set /p _vis=Input any desired vis settings, then press "Enter" to continue...
Echo.
Call docs\lightdescription.bat
Set /P _light=Input any desired light settings. Pres "Enter" to continue...
Echo.

:Run

Echo ::Generated by Qompilerv0.80>configs\%_config%.bat
Echo set _vis=%_vis%>>configs\%_config%.bat
Echo set _qbsp=%_qbsp%>>configs\%_config%.bat
Echo set _light=%_light%>>configs\%_config%.bat
Echo End of log.>>Logs\QompilerLog.txt
For %%i in (*.MAP) do call Qompiler DoIt %%i
Echo.


:Qompile
Echo Qompiling map %2...
Echo Qompiling %2>>Logs\QompilerLog.txt
tools\qbsp.exe %_qbsp% %2>>Logs\QompilerLog.txt
tools\vis.exe %_vis% %2>>Logs\QompilerLog.txt
tools\light.exe %_light% %2>>Logs\QompilerLog.txt
Echo Finished map %2>>Logs\QompilerLog.txt
Echo.>>Logs\QompilerLog.txt
Echo.>>Logs\QompilerLog.txt
Echo.>>Logs\QompilerLog.txt
Echo %2>>Logs\Qompiled.txt
Move %2 Qompiled>Nul
If Exist "*.Prt" Del "*.Prt">Nul
If Exist "*.bsp" Move "*.bsp" Maps>Nul
If Exist "*.lit" Move "*.lit" Maps>Nul
If Exist "*.log" Move "*.log" Logs>Nul
Echo.
Echo Qompiling successful..
Pause
GoTo End

:NeedMaps
Echo. Qompiler and your maps must be in the same folder.  
Echo. Be sure your compiling tools are in the Tools directory, as well.
Goto Restart

:Restart
Echo Do you wish to restart? 
Echo.
Set /p op=Choose Y/N...
if /I "%op%"=="y" goto Start
) else (
goto End

:NoTools
Echo. Need qbsp.exe/vis.exe/light.exe in the Tools directory.
Goto Restart

:End
